/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as TenantRouteImport } from './routes/_tenant'
import { Route as TenantStudentRouteImport } from './routes/_tenant/student'
import { Route as TenantLoginRouteImport } from './routes/_tenant/login'
import { Route as TenantAdminRouteImport } from './routes/_tenant/admin'
import { Route as TenantPublicRouteImport } from './routes/_tenant/_public'
import { Route as TenantAuthRouteImport } from './routes/_tenant/_auth'
import { Route as TenantStudentIndexRouteImport } from './routes/_tenant/student/index'
import { Route as TenantAdminIndexRouteImport } from './routes/_tenant/admin/index'
import { Route as TenantPublicIndexRouteImport } from './routes/_tenant/_public/index'
import { Route as TenantStudentProgressRouteImport } from './routes/_tenant/student/progress'
import { Route as TenantStudentProfileRouteImport } from './routes/_tenant/student/profile'
import { Route as TenantStudentLiveSessionsRouteImport } from './routes/_tenant/student/live-sessions'
import { Route as TenantStudentCoursesRouteImport } from './routes/_tenant/student/courses'
import { Route as TenantAdminUsersRouteImport } from './routes/_tenant/admin/users'
import { Route as TenantAdminSettingsRouteImport } from './routes/_tenant/admin/settings'
import { Route as TenantAdminSecurityRouteImport } from './routes/_tenant/admin/security'
import { Route as TenantAdminProfileRouteImport } from './routes/_tenant/admin/profile'
import { Route as TenantAdminLiveSessionsRouteImport } from './routes/_tenant/admin/live-sessions'
import { Route as TenantAdminCoursesRouteImport } from './routes/_tenant/admin/courses'
import { Route as TenantAdminCertificatesRouteImport } from './routes/_tenant/admin/certificates'
import { Route as TenantAdminAnalyticsRouteImport } from './routes/_tenant/admin/analytics'
import { Route as TenantPublicVerifyCertificateRouteImport } from './routes/_tenant/_public/verify-certificate'
import { Route as TenantStudentCoursesCourseIdRouteImport } from './routes/_tenant/student/courses/$courseId'
import { Route as TenantAdminUsersNewRouteImport } from './routes/_tenant/admin/users/new'
import { Route as TenantAdminUsersStudentIdRouteImport } from './routes/_tenant/admin/users/$studentId'
import { Route as TenantAdminAnalyticsReportsRouteImport } from './routes/_tenant/admin/analytics/reports'
import { Route as TenantStudentCoursesCourseIdLearnRouteImport } from './routes/_tenant/student/courses/$courseId/learn'
import { Route as TenantAdminUsersStudentIdProgressRouteImport } from './routes/_tenant/admin/users/$studentId/progress'
import { Route as TenantAdminCoursesCourseIdEditRouteImport } from './routes/_tenant/admin/courses/$courseId/edit'
import { Route as TenantStudentCoursesCourseIdQuizQuizIdRouteImport } from './routes/_tenant/student/courses/$courseId/quiz/$quizId'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRoute = TenantRouteImport.update({
  id: '/_tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantStudentRoute = TenantStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => TenantRoute,
} as any)
const TenantLoginRoute = TenantLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => TenantRoute,
} as any)
const TenantAdminRoute = TenantAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => TenantRoute,
} as any)
const TenantPublicRoute = TenantPublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => TenantRoute,
} as any)
const TenantAuthRoute = TenantAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStudentIndexRoute = TenantStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantStudentRoute,
} as any)
const TenantAdminIndexRoute = TenantAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantPublicIndexRoute = TenantPublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantPublicRoute,
} as any)
const TenantStudentProgressRoute = TenantStudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => TenantStudentRoute,
} as any)
const TenantStudentProfileRoute = TenantStudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TenantStudentRoute,
} as any)
const TenantStudentLiveSessionsRoute =
  TenantStudentLiveSessionsRouteImport.update({
    id: '/live-sessions',
    path: '/live-sessions',
    getParentRoute: () => TenantStudentRoute,
  } as any)
const TenantStudentCoursesRoute = TenantStudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => TenantStudentRoute,
} as any)
const TenantAdminUsersRoute = TenantAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminSettingsRoute = TenantAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminSecurityRoute = TenantAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminProfileRoute = TenantAdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminLiveSessionsRoute = TenantAdminLiveSessionsRouteImport.update({
  id: '/live-sessions',
  path: '/live-sessions',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminCoursesRoute = TenantAdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminCertificatesRoute = TenantAdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminAnalyticsRoute = TenantAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantPublicVerifyCertificateRoute =
  TenantPublicVerifyCertificateRouteImport.update({
    id: '/verify-certificate',
    path: '/verify-certificate',
    getParentRoute: () => TenantPublicRoute,
  } as any)
const TenantStudentCoursesCourseIdRoute =
  TenantStudentCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => TenantStudentCoursesRoute,
  } as any)
const TenantAdminUsersNewRoute = TenantAdminUsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TenantAdminUsersRoute,
} as any)
const TenantAdminUsersStudentIdRoute =
  TenantAdminUsersStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => TenantAdminUsersRoute,
  } as any)
const TenantAdminAnalyticsReportsRoute =
  TenantAdminAnalyticsReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => TenantAdminAnalyticsRoute,
  } as any)
const TenantStudentCoursesCourseIdLearnRoute =
  TenantStudentCoursesCourseIdLearnRouteImport.update({
    id: '/learn',
    path: '/learn',
    getParentRoute: () => TenantStudentCoursesCourseIdRoute,
  } as any)
const TenantAdminUsersStudentIdProgressRoute =
  TenantAdminUsersStudentIdProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => TenantAdminUsersStudentIdRoute,
  } as any)
const TenantAdminCoursesCourseIdEditRoute =
  TenantAdminCoursesCourseIdEditRouteImport.update({
    id: '/$courseId/edit',
    path: '/$courseId/edit',
    getParentRoute: () => TenantAdminCoursesRoute,
  } as any)
const TenantStudentCoursesCourseIdQuizQuizIdRoute =
  TenantStudentCoursesCourseIdQuizQuizIdRouteImport.update({
    id: '/quiz/$quizId',
    path: '/quiz/$quizId',
    getParentRoute: () => TenantStudentCoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/super-admin': typeof SuperAdminRoute
  '/admin': typeof TenantAdminRouteWithChildren
  '/login': typeof TenantLoginRoute
  '/student': typeof TenantStudentRouteWithChildren
  '/verify-certificate': typeof TenantPublicVerifyCertificateRoute
  '/admin/analytics': typeof TenantAdminAnalyticsRouteWithChildren
  '/admin/certificates': typeof TenantAdminCertificatesRoute
  '/admin/courses': typeof TenantAdminCoursesRouteWithChildren
  '/admin/live-sessions': typeof TenantAdminLiveSessionsRoute
  '/admin/profile': typeof TenantAdminProfileRoute
  '/admin/security': typeof TenantAdminSecurityRoute
  '/admin/settings': typeof TenantAdminSettingsRoute
  '/admin/users': typeof TenantAdminUsersRouteWithChildren
  '/student/courses': typeof TenantStudentCoursesRouteWithChildren
  '/student/live-sessions': typeof TenantStudentLiveSessionsRoute
  '/student/profile': typeof TenantStudentProfileRoute
  '/student/progress': typeof TenantStudentProgressRoute
  '/': typeof TenantPublicIndexRoute
  '/admin/': typeof TenantAdminIndexRoute
  '/student/': typeof TenantStudentIndexRoute
  '/admin/analytics/reports': typeof TenantAdminAnalyticsReportsRoute
  '/admin/users/$studentId': typeof TenantAdminUsersStudentIdRouteWithChildren
  '/admin/users/new': typeof TenantAdminUsersNewRoute
  '/student/courses/$courseId': typeof TenantStudentCoursesCourseIdRouteWithChildren
  '/admin/courses/$courseId/edit': typeof TenantAdminCoursesCourseIdEditRoute
  '/admin/users/$studentId/progress': typeof TenantAdminUsersStudentIdProgressRoute
  '/student/courses/$courseId/learn': typeof TenantStudentCoursesCourseIdLearnRoute
  '/student/courses/$courseId/quiz/$quizId': typeof TenantStudentCoursesCourseIdQuizQuizIdRoute
}
export interface FileRoutesByTo {
  '/super-admin': typeof SuperAdminRoute
  '/login': typeof TenantLoginRoute
  '/verify-certificate': typeof TenantPublicVerifyCertificateRoute
  '/admin/analytics': typeof TenantAdminAnalyticsRouteWithChildren
  '/admin/certificates': typeof TenantAdminCertificatesRoute
  '/admin/courses': typeof TenantAdminCoursesRouteWithChildren
  '/admin/live-sessions': typeof TenantAdminLiveSessionsRoute
  '/admin/profile': typeof TenantAdminProfileRoute
  '/admin/security': typeof TenantAdminSecurityRoute
  '/admin/settings': typeof TenantAdminSettingsRoute
  '/admin/users': typeof TenantAdminUsersRouteWithChildren
  '/student/courses': typeof TenantStudentCoursesRouteWithChildren
  '/student/live-sessions': typeof TenantStudentLiveSessionsRoute
  '/student/profile': typeof TenantStudentProfileRoute
  '/student/progress': typeof TenantStudentProgressRoute
  '/': typeof TenantPublicIndexRoute
  '/admin': typeof TenantAdminIndexRoute
  '/student': typeof TenantStudentIndexRoute
  '/admin/analytics/reports': typeof TenantAdminAnalyticsReportsRoute
  '/admin/users/$studentId': typeof TenantAdminUsersStudentIdRouteWithChildren
  '/admin/users/new': typeof TenantAdminUsersNewRoute
  '/student/courses/$courseId': typeof TenantStudentCoursesCourseIdRouteWithChildren
  '/admin/courses/$courseId/edit': typeof TenantAdminCoursesCourseIdEditRoute
  '/admin/users/$studentId/progress': typeof TenantAdminUsersStudentIdProgressRoute
  '/student/courses/$courseId/learn': typeof TenantStudentCoursesCourseIdLearnRoute
  '/student/courses/$courseId/quiz/$quizId': typeof TenantStudentCoursesCourseIdQuizQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_tenant': typeof TenantRouteWithChildren
  '/super-admin': typeof SuperAdminRoute
  '/_tenant/_auth': typeof TenantAuthRoute
  '/_tenant/_public': typeof TenantPublicRouteWithChildren
  '/_tenant/admin': typeof TenantAdminRouteWithChildren
  '/_tenant/login': typeof TenantLoginRoute
  '/_tenant/student': typeof TenantStudentRouteWithChildren
  '/_tenant/_public/verify-certificate': typeof TenantPublicVerifyCertificateRoute
  '/_tenant/admin/analytics': typeof TenantAdminAnalyticsRouteWithChildren
  '/_tenant/admin/certificates': typeof TenantAdminCertificatesRoute
  '/_tenant/admin/courses': typeof TenantAdminCoursesRouteWithChildren
  '/_tenant/admin/live-sessions': typeof TenantAdminLiveSessionsRoute
  '/_tenant/admin/profile': typeof TenantAdminProfileRoute
  '/_tenant/admin/security': typeof TenantAdminSecurityRoute
  '/_tenant/admin/settings': typeof TenantAdminSettingsRoute
  '/_tenant/admin/users': typeof TenantAdminUsersRouteWithChildren
  '/_tenant/student/courses': typeof TenantStudentCoursesRouteWithChildren
  '/_tenant/student/live-sessions': typeof TenantStudentLiveSessionsRoute
  '/_tenant/student/profile': typeof TenantStudentProfileRoute
  '/_tenant/student/progress': typeof TenantStudentProgressRoute
  '/_tenant/_public/': typeof TenantPublicIndexRoute
  '/_tenant/admin/': typeof TenantAdminIndexRoute
  '/_tenant/student/': typeof TenantStudentIndexRoute
  '/_tenant/admin/analytics/reports': typeof TenantAdminAnalyticsReportsRoute
  '/_tenant/admin/users/$studentId': typeof TenantAdminUsersStudentIdRouteWithChildren
  '/_tenant/admin/users/new': typeof TenantAdminUsersNewRoute
  '/_tenant/student/courses/$courseId': typeof TenantStudentCoursesCourseIdRouteWithChildren
  '/_tenant/admin/courses/$courseId/edit': typeof TenantAdminCoursesCourseIdEditRoute
  '/_tenant/admin/users/$studentId/progress': typeof TenantAdminUsersStudentIdProgressRoute
  '/_tenant/student/courses/$courseId/learn': typeof TenantStudentCoursesCourseIdLearnRoute
  '/_tenant/student/courses/$courseId/quiz/$quizId': typeof TenantStudentCoursesCourseIdQuizQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/super-admin'
    | '/admin'
    | '/login'
    | '/student'
    | '/verify-certificate'
    | '/admin/analytics'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/live-sessions'
    | '/admin/profile'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/student/courses'
    | '/student/live-sessions'
    | '/student/profile'
    | '/student/progress'
    | '/'
    | '/admin/'
    | '/student/'
    | '/admin/analytics/reports'
    | '/admin/users/$studentId'
    | '/admin/users/new'
    | '/student/courses/$courseId'
    | '/admin/courses/$courseId/edit'
    | '/admin/users/$studentId/progress'
    | '/student/courses/$courseId/learn'
    | '/student/courses/$courseId/quiz/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/super-admin'
    | '/login'
    | '/verify-certificate'
    | '/admin/analytics'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/live-sessions'
    | '/admin/profile'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/student/courses'
    | '/student/live-sessions'
    | '/student/profile'
    | '/student/progress'
    | '/'
    | '/admin'
    | '/student'
    | '/admin/analytics/reports'
    | '/admin/users/$studentId'
    | '/admin/users/new'
    | '/student/courses/$courseId'
    | '/admin/courses/$courseId/edit'
    | '/admin/users/$studentId/progress'
    | '/student/courses/$courseId/learn'
    | '/student/courses/$courseId/quiz/$quizId'
  id:
    | '__root__'
    | '/_tenant'
    | '/super-admin'
    | '/_tenant/_auth'
    | '/_tenant/_public'
    | '/_tenant/admin'
    | '/_tenant/login'
    | '/_tenant/student'
    | '/_tenant/_public/verify-certificate'
    | '/_tenant/admin/analytics'
    | '/_tenant/admin/certificates'
    | '/_tenant/admin/courses'
    | '/_tenant/admin/live-sessions'
    | '/_tenant/admin/profile'
    | '/_tenant/admin/security'
    | '/_tenant/admin/settings'
    | '/_tenant/admin/users'
    | '/_tenant/student/courses'
    | '/_tenant/student/live-sessions'
    | '/_tenant/student/profile'
    | '/_tenant/student/progress'
    | '/_tenant/_public/'
    | '/_tenant/admin/'
    | '/_tenant/student/'
    | '/_tenant/admin/analytics/reports'
    | '/_tenant/admin/users/$studentId'
    | '/_tenant/admin/users/new'
    | '/_tenant/student/courses/$courseId'
    | '/_tenant/admin/courses/$courseId/edit'
    | '/_tenant/admin/users/$studentId/progress'
    | '/_tenant/student/courses/$courseId/learn'
    | '/_tenant/student/courses/$courseId/quiz/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TenantRoute: typeof TenantRouteWithChildren
  SuperAdminRoute: typeof SuperAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tenant': {
      id: '/_tenant'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tenant/student': {
      id: '/_tenant/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof TenantStudentRouteImport
      parentRoute: typeof TenantRoute
    }
    '/_tenant/login': {
      id: '/_tenant/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof TenantLoginRouteImport
      parentRoute: typeof TenantRoute
    }
    '/_tenant/admin': {
      id: '/_tenant/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof TenantAdminRouteImport
      parentRoute: typeof TenantRoute
    }
    '/_tenant/_public': {
      id: '/_tenant/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof TenantPublicRouteImport
      parentRoute: typeof TenantRoute
    }
    '/_tenant/_auth': {
      id: '/_tenant/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof TenantAuthRouteImport
      parentRoute: typeof TenantRoute
    }
    '/_tenant/student/': {
      id: '/_tenant/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof TenantStudentIndexRouteImport
      parentRoute: typeof TenantStudentRoute
    }
    '/_tenant/admin/': {
      id: '/_tenant/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof TenantAdminIndexRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/_tenant/_public/': {
      id: '/_tenant/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TenantPublicIndexRouteImport
      parentRoute: typeof TenantPublicRoute
    }
    '/_tenant/student/progress': {
      id: '/_tenant/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof TenantStudentProgressRouteImport
      parentRoute: typeof TenantStudentRoute
    }
    '/_tenant/student/profile': {
      id: '/_tenant/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof TenantStudentProfileRouteImport
      parentRoute: typeof TenantStudentRoute
    }
    '/_tenant/student/live-sessions': {
      id: '/_tenant/student/live-sessions'
      path: '/live-sessions'
      fullPath: '/student/live-sessions'
      preLoaderRoute: typeof TenantStudentLiveSessionsRouteImport
      parentRoute: typeof TenantStudentRoute
    }
    '/_tenant/student/courses': {
      id: '/_tenant/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof TenantStudentCoursesRouteImport
      parentRoute: typeof TenantStudentRoute
    }
    '/_tenant/admin/users': {
      id: '/_tenant/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof TenantAdminUsersRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/_tenant/admin/settings': {
      id: '/_tenant/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof TenantAdminSettingsRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/_tenant/admin/security': {
      id: '/_tenant/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof TenantAdminSecurityRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/_tenant/admin/profile': {
      id: '/_tenant/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof TenantAdminProfileRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/_tenant/admin/live-sessions': {
      id: '/_tenant/admin/live-sessions'
      path: '/live-sessions'
      fullPath: '/admin/live-sessions'
      preLoaderRoute: typeof TenantAdminLiveSessionsRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/_tenant/admin/courses': {
      id: '/_tenant/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof TenantAdminCoursesRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/_tenant/admin/certificates': {
      id: '/_tenant/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof TenantAdminCertificatesRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/_tenant/admin/analytics': {
      id: '/_tenant/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof TenantAdminAnalyticsRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/_tenant/_public/verify-certificate': {
      id: '/_tenant/_public/verify-certificate'
      path: '/verify-certificate'
      fullPath: '/verify-certificate'
      preLoaderRoute: typeof TenantPublicVerifyCertificateRouteImport
      parentRoute: typeof TenantPublicRoute
    }
    '/_tenant/student/courses/$courseId': {
      id: '/_tenant/student/courses/$courseId'
      path: '/$courseId'
      fullPath: '/student/courses/$courseId'
      preLoaderRoute: typeof TenantStudentCoursesCourseIdRouteImport
      parentRoute: typeof TenantStudentCoursesRoute
    }
    '/_tenant/admin/users/new': {
      id: '/_tenant/admin/users/new'
      path: '/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof TenantAdminUsersNewRouteImport
      parentRoute: typeof TenantAdminUsersRoute
    }
    '/_tenant/admin/users/$studentId': {
      id: '/_tenant/admin/users/$studentId'
      path: '/$studentId'
      fullPath: '/admin/users/$studentId'
      preLoaderRoute: typeof TenantAdminUsersStudentIdRouteImport
      parentRoute: typeof TenantAdminUsersRoute
    }
    '/_tenant/admin/analytics/reports': {
      id: '/_tenant/admin/analytics/reports'
      path: '/reports'
      fullPath: '/admin/analytics/reports'
      preLoaderRoute: typeof TenantAdminAnalyticsReportsRouteImport
      parentRoute: typeof TenantAdminAnalyticsRoute
    }
    '/_tenant/student/courses/$courseId/learn': {
      id: '/_tenant/student/courses/$courseId/learn'
      path: '/learn'
      fullPath: '/student/courses/$courseId/learn'
      preLoaderRoute: typeof TenantStudentCoursesCourseIdLearnRouteImport
      parentRoute: typeof TenantStudentCoursesCourseIdRoute
    }
    '/_tenant/admin/users/$studentId/progress': {
      id: '/_tenant/admin/users/$studentId/progress'
      path: '/progress'
      fullPath: '/admin/users/$studentId/progress'
      preLoaderRoute: typeof TenantAdminUsersStudentIdProgressRouteImport
      parentRoute: typeof TenantAdminUsersStudentIdRoute
    }
    '/_tenant/admin/courses/$courseId/edit': {
      id: '/_tenant/admin/courses/$courseId/edit'
      path: '/$courseId/edit'
      fullPath: '/admin/courses/$courseId/edit'
      preLoaderRoute: typeof TenantAdminCoursesCourseIdEditRouteImport
      parentRoute: typeof TenantAdminCoursesRoute
    }
    '/_tenant/student/courses/$courseId/quiz/$quizId': {
      id: '/_tenant/student/courses/$courseId/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/student/courses/$courseId/quiz/$quizId'
      preLoaderRoute: typeof TenantStudentCoursesCourseIdQuizQuizIdRouteImport
      parentRoute: typeof TenantStudentCoursesCourseIdRoute
    }
  }
}

interface TenantPublicRouteChildren {
  TenantPublicVerifyCertificateRoute: typeof TenantPublicVerifyCertificateRoute
  TenantPublicIndexRoute: typeof TenantPublicIndexRoute
}

const TenantPublicRouteChildren: TenantPublicRouteChildren = {
  TenantPublicVerifyCertificateRoute: TenantPublicVerifyCertificateRoute,
  TenantPublicIndexRoute: TenantPublicIndexRoute,
}

const TenantPublicRouteWithChildren = TenantPublicRoute._addFileChildren(
  TenantPublicRouteChildren,
)

interface TenantAdminAnalyticsRouteChildren {
  TenantAdminAnalyticsReportsRoute: typeof TenantAdminAnalyticsReportsRoute
}

const TenantAdminAnalyticsRouteChildren: TenantAdminAnalyticsRouteChildren = {
  TenantAdminAnalyticsReportsRoute: TenantAdminAnalyticsReportsRoute,
}

const TenantAdminAnalyticsRouteWithChildren =
  TenantAdminAnalyticsRoute._addFileChildren(TenantAdminAnalyticsRouteChildren)

interface TenantAdminCoursesRouteChildren {
  TenantAdminCoursesCourseIdEditRoute: typeof TenantAdminCoursesCourseIdEditRoute
}

const TenantAdminCoursesRouteChildren: TenantAdminCoursesRouteChildren = {
  TenantAdminCoursesCourseIdEditRoute: TenantAdminCoursesCourseIdEditRoute,
}

const TenantAdminCoursesRouteWithChildren =
  TenantAdminCoursesRoute._addFileChildren(TenantAdminCoursesRouteChildren)

interface TenantAdminUsersStudentIdRouteChildren {
  TenantAdminUsersStudentIdProgressRoute: typeof TenantAdminUsersStudentIdProgressRoute
}

const TenantAdminUsersStudentIdRouteChildren: TenantAdminUsersStudentIdRouteChildren =
  {
    TenantAdminUsersStudentIdProgressRoute:
      TenantAdminUsersStudentIdProgressRoute,
  }

const TenantAdminUsersStudentIdRouteWithChildren =
  TenantAdminUsersStudentIdRoute._addFileChildren(
    TenantAdminUsersStudentIdRouteChildren,
  )

interface TenantAdminUsersRouteChildren {
  TenantAdminUsersStudentIdRoute: typeof TenantAdminUsersStudentIdRouteWithChildren
  TenantAdminUsersNewRoute: typeof TenantAdminUsersNewRoute
}

const TenantAdminUsersRouteChildren: TenantAdminUsersRouteChildren = {
  TenantAdminUsersStudentIdRoute: TenantAdminUsersStudentIdRouteWithChildren,
  TenantAdminUsersNewRoute: TenantAdminUsersNewRoute,
}

const TenantAdminUsersRouteWithChildren =
  TenantAdminUsersRoute._addFileChildren(TenantAdminUsersRouteChildren)

interface TenantAdminRouteChildren {
  TenantAdminAnalyticsRoute: typeof TenantAdminAnalyticsRouteWithChildren
  TenantAdminCertificatesRoute: typeof TenantAdminCertificatesRoute
  TenantAdminCoursesRoute: typeof TenantAdminCoursesRouteWithChildren
  TenantAdminLiveSessionsRoute: typeof TenantAdminLiveSessionsRoute
  TenantAdminProfileRoute: typeof TenantAdminProfileRoute
  TenantAdminSecurityRoute: typeof TenantAdminSecurityRoute
  TenantAdminSettingsRoute: typeof TenantAdminSettingsRoute
  TenantAdminUsersRoute: typeof TenantAdminUsersRouteWithChildren
  TenantAdminIndexRoute: typeof TenantAdminIndexRoute
}

const TenantAdminRouteChildren: TenantAdminRouteChildren = {
  TenantAdminAnalyticsRoute: TenantAdminAnalyticsRouteWithChildren,
  TenantAdminCertificatesRoute: TenantAdminCertificatesRoute,
  TenantAdminCoursesRoute: TenantAdminCoursesRouteWithChildren,
  TenantAdminLiveSessionsRoute: TenantAdminLiveSessionsRoute,
  TenantAdminProfileRoute: TenantAdminProfileRoute,
  TenantAdminSecurityRoute: TenantAdminSecurityRoute,
  TenantAdminSettingsRoute: TenantAdminSettingsRoute,
  TenantAdminUsersRoute: TenantAdminUsersRouteWithChildren,
  TenantAdminIndexRoute: TenantAdminIndexRoute,
}

const TenantAdminRouteWithChildren = TenantAdminRoute._addFileChildren(
  TenantAdminRouteChildren,
)

interface TenantStudentCoursesCourseIdRouteChildren {
  TenantStudentCoursesCourseIdLearnRoute: typeof TenantStudentCoursesCourseIdLearnRoute
  TenantStudentCoursesCourseIdQuizQuizIdRoute: typeof TenantStudentCoursesCourseIdQuizQuizIdRoute
}

const TenantStudentCoursesCourseIdRouteChildren: TenantStudentCoursesCourseIdRouteChildren =
  {
    TenantStudentCoursesCourseIdLearnRoute:
      TenantStudentCoursesCourseIdLearnRoute,
    TenantStudentCoursesCourseIdQuizQuizIdRoute:
      TenantStudentCoursesCourseIdQuizQuizIdRoute,
  }

const TenantStudentCoursesCourseIdRouteWithChildren =
  TenantStudentCoursesCourseIdRoute._addFileChildren(
    TenantStudentCoursesCourseIdRouteChildren,
  )

interface TenantStudentCoursesRouteChildren {
  TenantStudentCoursesCourseIdRoute: typeof TenantStudentCoursesCourseIdRouteWithChildren
}

const TenantStudentCoursesRouteChildren: TenantStudentCoursesRouteChildren = {
  TenantStudentCoursesCourseIdRoute:
    TenantStudentCoursesCourseIdRouteWithChildren,
}

const TenantStudentCoursesRouteWithChildren =
  TenantStudentCoursesRoute._addFileChildren(TenantStudentCoursesRouteChildren)

interface TenantStudentRouteChildren {
  TenantStudentCoursesRoute: typeof TenantStudentCoursesRouteWithChildren
  TenantStudentLiveSessionsRoute: typeof TenantStudentLiveSessionsRoute
  TenantStudentProfileRoute: typeof TenantStudentProfileRoute
  TenantStudentProgressRoute: typeof TenantStudentProgressRoute
  TenantStudentIndexRoute: typeof TenantStudentIndexRoute
}

const TenantStudentRouteChildren: TenantStudentRouteChildren = {
  TenantStudentCoursesRoute: TenantStudentCoursesRouteWithChildren,
  TenantStudentLiveSessionsRoute: TenantStudentLiveSessionsRoute,
  TenantStudentProfileRoute: TenantStudentProfileRoute,
  TenantStudentProgressRoute: TenantStudentProgressRoute,
  TenantStudentIndexRoute: TenantStudentIndexRoute,
}

const TenantStudentRouteWithChildren = TenantStudentRoute._addFileChildren(
  TenantStudentRouteChildren,
)

interface TenantRouteChildren {
  TenantAuthRoute: typeof TenantAuthRoute
  TenantPublicRoute: typeof TenantPublicRouteWithChildren
  TenantAdminRoute: typeof TenantAdminRouteWithChildren
  TenantLoginRoute: typeof TenantLoginRoute
  TenantStudentRoute: typeof TenantStudentRouteWithChildren
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantAuthRoute: TenantAuthRoute,
  TenantPublicRoute: TenantPublicRouteWithChildren,
  TenantAdminRoute: TenantAdminRouteWithChildren,
  TenantLoginRoute: TenantLoginRoute,
  TenantStudentRoute: TenantStudentRouteWithChildren,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  TenantRoute: TenantRouteWithChildren,
  SuperAdminRoute: SuperAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
