/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyCertificateRouteImport } from './routes/verify-certificate'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TenantRouteImport } from './routes/$tenant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin/index'
import { Route as TenantIndexRouteImport } from './routes/$tenant/index'
import { Route as SuperAdminTenantsRouteImport } from './routes/super-admin/tenants'
import { Route as SuperAdminTelemetryRouteImport } from './routes/super-admin/telemetry'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin/settings'
import { Route as SuperAdminInvitationsRouteImport } from './routes/super-admin/invitations'
import { Route as SuperAdminIdentitiesRouteImport } from './routes/super-admin/identities'
import { Route as TenantStudentRouteImport } from './routes/$tenant/student'
import { Route as TenantLoginRouteImport } from './routes/$tenant/login'
import { Route as TenantAdminRouteImport } from './routes/$tenant/admin'
import { Route as TenantStudentIndexRouteImport } from './routes/$tenant/student/index'
import { Route as TenantAdminIndexRouteImport } from './routes/$tenant/admin/index'
import { Route as TenantStudentProgressRouteImport } from './routes/$tenant/student/progress'
import { Route as TenantStudentProfileRouteImport } from './routes/$tenant/student/profile'
import { Route as TenantStudentLiveSessionsRouteImport } from './routes/$tenant/student/live-sessions'
import { Route as TenantStudentCoursesRouteImport } from './routes/$tenant/student/courses'
import { Route as TenantAdminUsersRouteImport } from './routes/$tenant/admin/users'
import { Route as TenantAdminSettingsRouteImport } from './routes/$tenant/admin/settings'
import { Route as TenantAdminSecurityRouteImport } from './routes/$tenant/admin/security'
import { Route as TenantAdminQuizzesRouteImport } from './routes/$tenant/admin/quizzes'
import { Route as TenantAdminProfileRouteImport } from './routes/$tenant/admin/profile'
import { Route as TenantAdminLiveSessionsRouteImport } from './routes/$tenant/admin/live-sessions'
import { Route as TenantAdminCoursesRouteImport } from './routes/$tenant/admin/courses'
import { Route as TenantAdminCertificatesRouteImport } from './routes/$tenant/admin/certificates'
import { Route as TenantAdminAnalyticsRouteImport } from './routes/$tenant/admin/analytics'
import { Route as TenantStudentCoursesIndexRouteImport } from './routes/$tenant/student/courses/index'
import { Route as TenantAdminUsersIndexRouteImport } from './routes/$tenant/admin/users/index'
import { Route as TenantAdminQuizzesIndexRouteImport } from './routes/$tenant/admin/quizzes/index'
import { Route as TenantAdminCoursesIndexRouteImport } from './routes/$tenant/admin/courses/index'
import { Route as TenantStudentCoursesCourseIdRouteImport } from './routes/$tenant/student/courses/$courseId'
import { Route as TenantAdminUsersNewRouteImport } from './routes/$tenant/admin/users/new'
import { Route as TenantAdminUsersStudentIdRouteImport } from './routes/$tenant/admin/users/$studentId'
import { Route as TenantAdminQuizzesQuizIdRouteImport } from './routes/$tenant/admin/quizzes/$quizId'
import { Route as TenantStudentCoursesCourseIdIndexRouteImport } from './routes/$tenant/student/courses/$courseId/index'
import { Route as TenantAdminUsersStudentIdIndexRouteImport } from './routes/$tenant/admin/users/$studentId/index'
import { Route as TenantAdminQuizzesQuizIdIndexRouteImport } from './routes/$tenant/admin/quizzes/$quizId/index'
import { Route as TenantStudentCoursesCourseIdLearnRouteImport } from './routes/$tenant/student/courses/$courseId/learn'
import { Route as TenantAdminUsersStudentIdProgressRouteImport } from './routes/$tenant/admin/users/$studentId/progress'
import { Route as TenantAdminQuizzesQuizIdQuestionsRouteImport } from './routes/$tenant/admin/quizzes/$quizId/questions'
import { Route as TenantAdminCoursesCourseIdEditRouteImport } from './routes/$tenant/admin/courses/$courseId/edit'
import { Route as TenantStudentCoursesCourseIdQuizQuizIdRouteImport } from './routes/$tenant/student/courses/$courseId/quiz/$quizId'

const VerifyCertificateRoute = VerifyCertificateRouteImport.update({
  id: '/verify-certificate',
  path: '/verify-certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRoute = TenantRouteImport.update({
  id: '/$tenant',
  path: '/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantRoute,
} as any)
const SuperAdminTenantsRoute = SuperAdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminTelemetryRoute = SuperAdminTelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminInvitationsRoute = SuperAdminInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminIdentitiesRoute = SuperAdminIdentitiesRouteImport.update({
  id: '/identities',
  path: '/identities',
  getParentRoute: () => SuperAdminRoute,
} as any)
const TenantStudentRoute = TenantStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => TenantRoute,
} as any)
const TenantLoginRoute = TenantLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => TenantRoute,
} as any)
const TenantAdminRoute = TenantAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => TenantRoute,
} as any)
const TenantStudentIndexRoute = TenantStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantStudentRoute,
} as any)
const TenantAdminIndexRoute = TenantAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantStudentProgressRoute = TenantStudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => TenantStudentRoute,
} as any)
const TenantStudentProfileRoute = TenantStudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TenantStudentRoute,
} as any)
const TenantStudentLiveSessionsRoute =
  TenantStudentLiveSessionsRouteImport.update({
    id: '/live-sessions',
    path: '/live-sessions',
    getParentRoute: () => TenantStudentRoute,
  } as any)
const TenantStudentCoursesRoute = TenantStudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => TenantStudentRoute,
} as any)
const TenantAdminUsersRoute = TenantAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminSettingsRoute = TenantAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminSecurityRoute = TenantAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminQuizzesRoute = TenantAdminQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminProfileRoute = TenantAdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminLiveSessionsRoute = TenantAdminLiveSessionsRouteImport.update({
  id: '/live-sessions',
  path: '/live-sessions',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminCoursesRoute = TenantAdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminCertificatesRoute = TenantAdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantAdminAnalyticsRoute = TenantAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => TenantAdminRoute,
} as any)
const TenantStudentCoursesIndexRoute =
  TenantStudentCoursesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TenantStudentCoursesRoute,
  } as any)
const TenantAdminUsersIndexRoute = TenantAdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantAdminUsersRoute,
} as any)
const TenantAdminQuizzesIndexRoute = TenantAdminQuizzesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantAdminQuizzesRoute,
} as any)
const TenantAdminCoursesIndexRoute = TenantAdminCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantAdminCoursesRoute,
} as any)
const TenantStudentCoursesCourseIdRoute =
  TenantStudentCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => TenantStudentCoursesRoute,
  } as any)
const TenantAdminUsersNewRoute = TenantAdminUsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TenantAdminUsersRoute,
} as any)
const TenantAdminUsersStudentIdRoute =
  TenantAdminUsersStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => TenantAdminUsersRoute,
  } as any)
const TenantAdminQuizzesQuizIdRoute =
  TenantAdminQuizzesQuizIdRouteImport.update({
    id: '/$quizId',
    path: '/$quizId',
    getParentRoute: () => TenantAdminQuizzesRoute,
  } as any)
const TenantStudentCoursesCourseIdIndexRoute =
  TenantStudentCoursesCourseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TenantStudentCoursesCourseIdRoute,
  } as any)
const TenantAdminUsersStudentIdIndexRoute =
  TenantAdminUsersStudentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TenantAdminUsersStudentIdRoute,
  } as any)
const TenantAdminQuizzesQuizIdIndexRoute =
  TenantAdminQuizzesQuizIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TenantAdminQuizzesQuizIdRoute,
  } as any)
const TenantStudentCoursesCourseIdLearnRoute =
  TenantStudentCoursesCourseIdLearnRouteImport.update({
    id: '/learn',
    path: '/learn',
    getParentRoute: () => TenantStudentCoursesCourseIdRoute,
  } as any)
const TenantAdminUsersStudentIdProgressRoute =
  TenantAdminUsersStudentIdProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => TenantAdminUsersStudentIdRoute,
  } as any)
const TenantAdminQuizzesQuizIdQuestionsRoute =
  TenantAdminQuizzesQuizIdQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => TenantAdminQuizzesQuizIdRoute,
  } as any)
const TenantAdminCoursesCourseIdEditRoute =
  TenantAdminCoursesCourseIdEditRouteImport.update({
    id: '/$courseId/edit',
    path: '/$courseId/edit',
    getParentRoute: () => TenantAdminCoursesRoute,
  } as any)
const TenantStudentCoursesCourseIdQuizQuizIdRoute =
  TenantStudentCoursesCourseIdQuizQuizIdRouteImport.update({
    id: '/quiz/$quizId',
    path: '/quiz/$quizId',
    getParentRoute: () => TenantStudentCoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tenant': typeof TenantRouteWithChildren
  '/login': typeof LoginRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/verify-certificate': typeof VerifyCertificateRoute
  '/$tenant/admin': typeof TenantAdminRouteWithChildren
  '/$tenant/login': typeof TenantLoginRoute
  '/$tenant/student': typeof TenantStudentRouteWithChildren
  '/super-admin/identities': typeof SuperAdminIdentitiesRoute
  '/super-admin/invitations': typeof SuperAdminInvitationsRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/telemetry': typeof SuperAdminTelemetryRoute
  '/super-admin/tenants': typeof SuperAdminTenantsRoute
  '/$tenant/': typeof TenantIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/$tenant/admin/analytics': typeof TenantAdminAnalyticsRoute
  '/$tenant/admin/certificates': typeof TenantAdminCertificatesRoute
  '/$tenant/admin/courses': typeof TenantAdminCoursesRouteWithChildren
  '/$tenant/admin/live-sessions': typeof TenantAdminLiveSessionsRoute
  '/$tenant/admin/profile': typeof TenantAdminProfileRoute
  '/$tenant/admin/quizzes': typeof TenantAdminQuizzesRouteWithChildren
  '/$tenant/admin/security': typeof TenantAdminSecurityRoute
  '/$tenant/admin/settings': typeof TenantAdminSettingsRoute
  '/$tenant/admin/users': typeof TenantAdminUsersRouteWithChildren
  '/$tenant/student/courses': typeof TenantStudentCoursesRouteWithChildren
  '/$tenant/student/live-sessions': typeof TenantStudentLiveSessionsRoute
  '/$tenant/student/profile': typeof TenantStudentProfileRoute
  '/$tenant/student/progress': typeof TenantStudentProgressRoute
  '/$tenant/admin/': typeof TenantAdminIndexRoute
  '/$tenant/student/': typeof TenantStudentIndexRoute
  '/$tenant/admin/quizzes/$quizId': typeof TenantAdminQuizzesQuizIdRouteWithChildren
  '/$tenant/admin/users/$studentId': typeof TenantAdminUsersStudentIdRouteWithChildren
  '/$tenant/admin/users/new': typeof TenantAdminUsersNewRoute
  '/$tenant/student/courses/$courseId': typeof TenantStudentCoursesCourseIdRouteWithChildren
  '/$tenant/admin/courses/': typeof TenantAdminCoursesIndexRoute
  '/$tenant/admin/quizzes/': typeof TenantAdminQuizzesIndexRoute
  '/$tenant/admin/users/': typeof TenantAdminUsersIndexRoute
  '/$tenant/student/courses/': typeof TenantStudentCoursesIndexRoute
  '/$tenant/admin/courses/$courseId/edit': typeof TenantAdminCoursesCourseIdEditRoute
  '/$tenant/admin/quizzes/$quizId/questions': typeof TenantAdminQuizzesQuizIdQuestionsRoute
  '/$tenant/admin/users/$studentId/progress': typeof TenantAdminUsersStudentIdProgressRoute
  '/$tenant/student/courses/$courseId/learn': typeof TenantStudentCoursesCourseIdLearnRoute
  '/$tenant/admin/quizzes/$quizId/': typeof TenantAdminQuizzesQuizIdIndexRoute
  '/$tenant/admin/users/$studentId/': typeof TenantAdminUsersStudentIdIndexRoute
  '/$tenant/student/courses/$courseId/': typeof TenantStudentCoursesCourseIdIndexRoute
  '/$tenant/student/courses/$courseId/quiz/$quizId': typeof TenantStudentCoursesCourseIdQuizQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/$tenant/login': typeof TenantLoginRoute
  '/super-admin/identities': typeof SuperAdminIdentitiesRoute
  '/super-admin/invitations': typeof SuperAdminInvitationsRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/telemetry': typeof SuperAdminTelemetryRoute
  '/super-admin/tenants': typeof SuperAdminTenantsRoute
  '/$tenant': typeof TenantIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/$tenant/admin/analytics': typeof TenantAdminAnalyticsRoute
  '/$tenant/admin/certificates': typeof TenantAdminCertificatesRoute
  '/$tenant/admin/live-sessions': typeof TenantAdminLiveSessionsRoute
  '/$tenant/admin/profile': typeof TenantAdminProfileRoute
  '/$tenant/admin/security': typeof TenantAdminSecurityRoute
  '/$tenant/admin/settings': typeof TenantAdminSettingsRoute
  '/$tenant/student/live-sessions': typeof TenantStudentLiveSessionsRoute
  '/$tenant/student/profile': typeof TenantStudentProfileRoute
  '/$tenant/student/progress': typeof TenantStudentProgressRoute
  '/$tenant/admin': typeof TenantAdminIndexRoute
  '/$tenant/student': typeof TenantStudentIndexRoute
  '/$tenant/admin/users/new': typeof TenantAdminUsersNewRoute
  '/$tenant/admin/courses': typeof TenantAdminCoursesIndexRoute
  '/$tenant/admin/quizzes': typeof TenantAdminQuizzesIndexRoute
  '/$tenant/admin/users': typeof TenantAdminUsersIndexRoute
  '/$tenant/student/courses': typeof TenantStudentCoursesIndexRoute
  '/$tenant/admin/courses/$courseId/edit': typeof TenantAdminCoursesCourseIdEditRoute
  '/$tenant/admin/quizzes/$quizId/questions': typeof TenantAdminQuizzesQuizIdQuestionsRoute
  '/$tenant/admin/users/$studentId/progress': typeof TenantAdminUsersStudentIdProgressRoute
  '/$tenant/student/courses/$courseId/learn': typeof TenantStudentCoursesCourseIdLearnRoute
  '/$tenant/admin/quizzes/$quizId': typeof TenantAdminQuizzesQuizIdIndexRoute
  '/$tenant/admin/users/$studentId': typeof TenantAdminUsersStudentIdIndexRoute
  '/$tenant/student/courses/$courseId': typeof TenantStudentCoursesCourseIdIndexRoute
  '/$tenant/student/courses/$courseId/quiz/$quizId': typeof TenantStudentCoursesCourseIdQuizQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$tenant': typeof TenantRouteWithChildren
  '/login': typeof LoginRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/verify-certificate': typeof VerifyCertificateRoute
  '/$tenant/admin': typeof TenantAdminRouteWithChildren
  '/$tenant/login': typeof TenantLoginRoute
  '/$tenant/student': typeof TenantStudentRouteWithChildren
  '/super-admin/identities': typeof SuperAdminIdentitiesRoute
  '/super-admin/invitations': typeof SuperAdminInvitationsRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/telemetry': typeof SuperAdminTelemetryRoute
  '/super-admin/tenants': typeof SuperAdminTenantsRoute
  '/$tenant/': typeof TenantIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/$tenant/admin/analytics': typeof TenantAdminAnalyticsRoute
  '/$tenant/admin/certificates': typeof TenantAdminCertificatesRoute
  '/$tenant/admin/courses': typeof TenantAdminCoursesRouteWithChildren
  '/$tenant/admin/live-sessions': typeof TenantAdminLiveSessionsRoute
  '/$tenant/admin/profile': typeof TenantAdminProfileRoute
  '/$tenant/admin/quizzes': typeof TenantAdminQuizzesRouteWithChildren
  '/$tenant/admin/security': typeof TenantAdminSecurityRoute
  '/$tenant/admin/settings': typeof TenantAdminSettingsRoute
  '/$tenant/admin/users': typeof TenantAdminUsersRouteWithChildren
  '/$tenant/student/courses': typeof TenantStudentCoursesRouteWithChildren
  '/$tenant/student/live-sessions': typeof TenantStudentLiveSessionsRoute
  '/$tenant/student/profile': typeof TenantStudentProfileRoute
  '/$tenant/student/progress': typeof TenantStudentProgressRoute
  '/$tenant/admin/': typeof TenantAdminIndexRoute
  '/$tenant/student/': typeof TenantStudentIndexRoute
  '/$tenant/admin/quizzes/$quizId': typeof TenantAdminQuizzesQuizIdRouteWithChildren
  '/$tenant/admin/users/$studentId': typeof TenantAdminUsersStudentIdRouteWithChildren
  '/$tenant/admin/users/new': typeof TenantAdminUsersNewRoute
  '/$tenant/student/courses/$courseId': typeof TenantStudentCoursesCourseIdRouteWithChildren
  '/$tenant/admin/courses/': typeof TenantAdminCoursesIndexRoute
  '/$tenant/admin/quizzes/': typeof TenantAdminQuizzesIndexRoute
  '/$tenant/admin/users/': typeof TenantAdminUsersIndexRoute
  '/$tenant/student/courses/': typeof TenantStudentCoursesIndexRoute
  '/$tenant/admin/courses/$courseId/edit': typeof TenantAdminCoursesCourseIdEditRoute
  '/$tenant/admin/quizzes/$quizId/questions': typeof TenantAdminQuizzesQuizIdQuestionsRoute
  '/$tenant/admin/users/$studentId/progress': typeof TenantAdminUsersStudentIdProgressRoute
  '/$tenant/student/courses/$courseId/learn': typeof TenantStudentCoursesCourseIdLearnRoute
  '/$tenant/admin/quizzes/$quizId/': typeof TenantAdminQuizzesQuizIdIndexRoute
  '/$tenant/admin/users/$studentId/': typeof TenantAdminUsersStudentIdIndexRoute
  '/$tenant/student/courses/$courseId/': typeof TenantStudentCoursesCourseIdIndexRoute
  '/$tenant/student/courses/$courseId/quiz/$quizId': typeof TenantStudentCoursesCourseIdQuizQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$tenant'
    | '/login'
    | '/super-admin'
    | '/verify-certificate'
    | '/$tenant/admin'
    | '/$tenant/login'
    | '/$tenant/student'
    | '/super-admin/identities'
    | '/super-admin/invitations'
    | '/super-admin/settings'
    | '/super-admin/telemetry'
    | '/super-admin/tenants'
    | '/$tenant/'
    | '/super-admin/'
    | '/$tenant/admin/analytics'
    | '/$tenant/admin/certificates'
    | '/$tenant/admin/courses'
    | '/$tenant/admin/live-sessions'
    | '/$tenant/admin/profile'
    | '/$tenant/admin/quizzes'
    | '/$tenant/admin/security'
    | '/$tenant/admin/settings'
    | '/$tenant/admin/users'
    | '/$tenant/student/courses'
    | '/$tenant/student/live-sessions'
    | '/$tenant/student/profile'
    | '/$tenant/student/progress'
    | '/$tenant/admin/'
    | '/$tenant/student/'
    | '/$tenant/admin/quizzes/$quizId'
    | '/$tenant/admin/users/$studentId'
    | '/$tenant/admin/users/new'
    | '/$tenant/student/courses/$courseId'
    | '/$tenant/admin/courses/'
    | '/$tenant/admin/quizzes/'
    | '/$tenant/admin/users/'
    | '/$tenant/student/courses/'
    | '/$tenant/admin/courses/$courseId/edit'
    | '/$tenant/admin/quizzes/$quizId/questions'
    | '/$tenant/admin/users/$studentId/progress'
    | '/$tenant/student/courses/$courseId/learn'
    | '/$tenant/admin/quizzes/$quizId/'
    | '/$tenant/admin/users/$studentId/'
    | '/$tenant/student/courses/$courseId/'
    | '/$tenant/student/courses/$courseId/quiz/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/verify-certificate'
    | '/$tenant/login'
    | '/super-admin/identities'
    | '/super-admin/invitations'
    | '/super-admin/settings'
    | '/super-admin/telemetry'
    | '/super-admin/tenants'
    | '/$tenant'
    | '/super-admin'
    | '/$tenant/admin/analytics'
    | '/$tenant/admin/certificates'
    | '/$tenant/admin/live-sessions'
    | '/$tenant/admin/profile'
    | '/$tenant/admin/security'
    | '/$tenant/admin/settings'
    | '/$tenant/student/live-sessions'
    | '/$tenant/student/profile'
    | '/$tenant/student/progress'
    | '/$tenant/admin'
    | '/$tenant/student'
    | '/$tenant/admin/users/new'
    | '/$tenant/admin/courses'
    | '/$tenant/admin/quizzes'
    | '/$tenant/admin/users'
    | '/$tenant/student/courses'
    | '/$tenant/admin/courses/$courseId/edit'
    | '/$tenant/admin/quizzes/$quizId/questions'
    | '/$tenant/admin/users/$studentId/progress'
    | '/$tenant/student/courses/$courseId/learn'
    | '/$tenant/admin/quizzes/$quizId'
    | '/$tenant/admin/users/$studentId'
    | '/$tenant/student/courses/$courseId'
    | '/$tenant/student/courses/$courseId/quiz/$quizId'
  id:
    | '__root__'
    | '/'
    | '/$tenant'
    | '/login'
    | '/super-admin'
    | '/verify-certificate'
    | '/$tenant/admin'
    | '/$tenant/login'
    | '/$tenant/student'
    | '/super-admin/identities'
    | '/super-admin/invitations'
    | '/super-admin/settings'
    | '/super-admin/telemetry'
    | '/super-admin/tenants'
    | '/$tenant/'
    | '/super-admin/'
    | '/$tenant/admin/analytics'
    | '/$tenant/admin/certificates'
    | '/$tenant/admin/courses'
    | '/$tenant/admin/live-sessions'
    | '/$tenant/admin/profile'
    | '/$tenant/admin/quizzes'
    | '/$tenant/admin/security'
    | '/$tenant/admin/settings'
    | '/$tenant/admin/users'
    | '/$tenant/student/courses'
    | '/$tenant/student/live-sessions'
    | '/$tenant/student/profile'
    | '/$tenant/student/progress'
    | '/$tenant/admin/'
    | '/$tenant/student/'
    | '/$tenant/admin/quizzes/$quizId'
    | '/$tenant/admin/users/$studentId'
    | '/$tenant/admin/users/new'
    | '/$tenant/student/courses/$courseId'
    | '/$tenant/admin/courses/'
    | '/$tenant/admin/quizzes/'
    | '/$tenant/admin/users/'
    | '/$tenant/student/courses/'
    | '/$tenant/admin/courses/$courseId/edit'
    | '/$tenant/admin/quizzes/$quizId/questions'
    | '/$tenant/admin/users/$studentId/progress'
    | '/$tenant/student/courses/$courseId/learn'
    | '/$tenant/admin/quizzes/$quizId/'
    | '/$tenant/admin/users/$studentId/'
    | '/$tenant/student/courses/$courseId/'
    | '/$tenant/student/courses/$courseId/quiz/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenantRoute: typeof TenantRouteWithChildren
  LoginRoute: typeof LoginRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  VerifyCertificateRoute: typeof VerifyCertificateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-certificate': {
      id: '/verify-certificate'
      path: '/verify-certificate'
      fullPath: '/verify-certificate'
      preLoaderRoute: typeof VerifyCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant': {
      id: '/$tenant'
      path: '/$tenant'
      fullPath: '/$tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/$tenant/': {
      id: '/$tenant/'
      path: '/'
      fullPath: '/$tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof TenantRoute
    }
    '/super-admin/tenants': {
      id: '/super-admin/tenants'
      path: '/tenants'
      fullPath: '/super-admin/tenants'
      preLoaderRoute: typeof SuperAdminTenantsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/telemetry': {
      id: '/super-admin/telemetry'
      path: '/telemetry'
      fullPath: '/super-admin/telemetry'
      preLoaderRoute: typeof SuperAdminTelemetryRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/invitations': {
      id: '/super-admin/invitations'
      path: '/invitations'
      fullPath: '/super-admin/invitations'
      preLoaderRoute: typeof SuperAdminInvitationsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/identities': {
      id: '/super-admin/identities'
      path: '/identities'
      fullPath: '/super-admin/identities'
      preLoaderRoute: typeof SuperAdminIdentitiesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/$tenant/student': {
      id: '/$tenant/student'
      path: '/student'
      fullPath: '/$tenant/student'
      preLoaderRoute: typeof TenantStudentRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/login': {
      id: '/$tenant/login'
      path: '/login'
      fullPath: '/$tenant/login'
      preLoaderRoute: typeof TenantLoginRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/admin': {
      id: '/$tenant/admin'
      path: '/admin'
      fullPath: '/$tenant/admin'
      preLoaderRoute: typeof TenantAdminRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/student/': {
      id: '/$tenant/student/'
      path: '/'
      fullPath: '/$tenant/student/'
      preLoaderRoute: typeof TenantStudentIndexRouteImport
      parentRoute: typeof TenantStudentRoute
    }
    '/$tenant/admin/': {
      id: '/$tenant/admin/'
      path: '/'
      fullPath: '/$tenant/admin/'
      preLoaderRoute: typeof TenantAdminIndexRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/$tenant/student/progress': {
      id: '/$tenant/student/progress'
      path: '/progress'
      fullPath: '/$tenant/student/progress'
      preLoaderRoute: typeof TenantStudentProgressRouteImport
      parentRoute: typeof TenantStudentRoute
    }
    '/$tenant/student/profile': {
      id: '/$tenant/student/profile'
      path: '/profile'
      fullPath: '/$tenant/student/profile'
      preLoaderRoute: typeof TenantStudentProfileRouteImport
      parentRoute: typeof TenantStudentRoute
    }
    '/$tenant/student/live-sessions': {
      id: '/$tenant/student/live-sessions'
      path: '/live-sessions'
      fullPath: '/$tenant/student/live-sessions'
      preLoaderRoute: typeof TenantStudentLiveSessionsRouteImport
      parentRoute: typeof TenantStudentRoute
    }
    '/$tenant/student/courses': {
      id: '/$tenant/student/courses'
      path: '/courses'
      fullPath: '/$tenant/student/courses'
      preLoaderRoute: typeof TenantStudentCoursesRouteImport
      parentRoute: typeof TenantStudentRoute
    }
    '/$tenant/admin/users': {
      id: '/$tenant/admin/users'
      path: '/users'
      fullPath: '/$tenant/admin/users'
      preLoaderRoute: typeof TenantAdminUsersRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/$tenant/admin/settings': {
      id: '/$tenant/admin/settings'
      path: '/settings'
      fullPath: '/$tenant/admin/settings'
      preLoaderRoute: typeof TenantAdminSettingsRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/$tenant/admin/security': {
      id: '/$tenant/admin/security'
      path: '/security'
      fullPath: '/$tenant/admin/security'
      preLoaderRoute: typeof TenantAdminSecurityRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/$tenant/admin/quizzes': {
      id: '/$tenant/admin/quizzes'
      path: '/quizzes'
      fullPath: '/$tenant/admin/quizzes'
      preLoaderRoute: typeof TenantAdminQuizzesRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/$tenant/admin/profile': {
      id: '/$tenant/admin/profile'
      path: '/profile'
      fullPath: '/$tenant/admin/profile'
      preLoaderRoute: typeof TenantAdminProfileRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/$tenant/admin/live-sessions': {
      id: '/$tenant/admin/live-sessions'
      path: '/live-sessions'
      fullPath: '/$tenant/admin/live-sessions'
      preLoaderRoute: typeof TenantAdminLiveSessionsRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/$tenant/admin/courses': {
      id: '/$tenant/admin/courses'
      path: '/courses'
      fullPath: '/$tenant/admin/courses'
      preLoaderRoute: typeof TenantAdminCoursesRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/$tenant/admin/certificates': {
      id: '/$tenant/admin/certificates'
      path: '/certificates'
      fullPath: '/$tenant/admin/certificates'
      preLoaderRoute: typeof TenantAdminCertificatesRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/$tenant/admin/analytics': {
      id: '/$tenant/admin/analytics'
      path: '/analytics'
      fullPath: '/$tenant/admin/analytics'
      preLoaderRoute: typeof TenantAdminAnalyticsRouteImport
      parentRoute: typeof TenantAdminRoute
    }
    '/$tenant/student/courses/': {
      id: '/$tenant/student/courses/'
      path: '/'
      fullPath: '/$tenant/student/courses/'
      preLoaderRoute: typeof TenantStudentCoursesIndexRouteImport
      parentRoute: typeof TenantStudentCoursesRoute
    }
    '/$tenant/admin/users/': {
      id: '/$tenant/admin/users/'
      path: '/'
      fullPath: '/$tenant/admin/users/'
      preLoaderRoute: typeof TenantAdminUsersIndexRouteImport
      parentRoute: typeof TenantAdminUsersRoute
    }
    '/$tenant/admin/quizzes/': {
      id: '/$tenant/admin/quizzes/'
      path: '/'
      fullPath: '/$tenant/admin/quizzes/'
      preLoaderRoute: typeof TenantAdminQuizzesIndexRouteImport
      parentRoute: typeof TenantAdminQuizzesRoute
    }
    '/$tenant/admin/courses/': {
      id: '/$tenant/admin/courses/'
      path: '/'
      fullPath: '/$tenant/admin/courses/'
      preLoaderRoute: typeof TenantAdminCoursesIndexRouteImport
      parentRoute: typeof TenantAdminCoursesRoute
    }
    '/$tenant/student/courses/$courseId': {
      id: '/$tenant/student/courses/$courseId'
      path: '/$courseId'
      fullPath: '/$tenant/student/courses/$courseId'
      preLoaderRoute: typeof TenantStudentCoursesCourseIdRouteImport
      parentRoute: typeof TenantStudentCoursesRoute
    }
    '/$tenant/admin/users/new': {
      id: '/$tenant/admin/users/new'
      path: '/new'
      fullPath: '/$tenant/admin/users/new'
      preLoaderRoute: typeof TenantAdminUsersNewRouteImport
      parentRoute: typeof TenantAdminUsersRoute
    }
    '/$tenant/admin/users/$studentId': {
      id: '/$tenant/admin/users/$studentId'
      path: '/$studentId'
      fullPath: '/$tenant/admin/users/$studentId'
      preLoaderRoute: typeof TenantAdminUsersStudentIdRouteImport
      parentRoute: typeof TenantAdminUsersRoute
    }
    '/$tenant/admin/quizzes/$quizId': {
      id: '/$tenant/admin/quizzes/$quizId'
      path: '/$quizId'
      fullPath: '/$tenant/admin/quizzes/$quizId'
      preLoaderRoute: typeof TenantAdminQuizzesQuizIdRouteImport
      parentRoute: typeof TenantAdminQuizzesRoute
    }
    '/$tenant/student/courses/$courseId/': {
      id: '/$tenant/student/courses/$courseId/'
      path: '/'
      fullPath: '/$tenant/student/courses/$courseId/'
      preLoaderRoute: typeof TenantStudentCoursesCourseIdIndexRouteImport
      parentRoute: typeof TenantStudentCoursesCourseIdRoute
    }
    '/$tenant/admin/users/$studentId/': {
      id: '/$tenant/admin/users/$studentId/'
      path: '/'
      fullPath: '/$tenant/admin/users/$studentId/'
      preLoaderRoute: typeof TenantAdminUsersStudentIdIndexRouteImport
      parentRoute: typeof TenantAdminUsersStudentIdRoute
    }
    '/$tenant/admin/quizzes/$quizId/': {
      id: '/$tenant/admin/quizzes/$quizId/'
      path: '/'
      fullPath: '/$tenant/admin/quizzes/$quizId/'
      preLoaderRoute: typeof TenantAdminQuizzesQuizIdIndexRouteImport
      parentRoute: typeof TenantAdminQuizzesQuizIdRoute
    }
    '/$tenant/student/courses/$courseId/learn': {
      id: '/$tenant/student/courses/$courseId/learn'
      path: '/learn'
      fullPath: '/$tenant/student/courses/$courseId/learn'
      preLoaderRoute: typeof TenantStudentCoursesCourseIdLearnRouteImport
      parentRoute: typeof TenantStudentCoursesCourseIdRoute
    }
    '/$tenant/admin/users/$studentId/progress': {
      id: '/$tenant/admin/users/$studentId/progress'
      path: '/progress'
      fullPath: '/$tenant/admin/users/$studentId/progress'
      preLoaderRoute: typeof TenantAdminUsersStudentIdProgressRouteImport
      parentRoute: typeof TenantAdminUsersStudentIdRoute
    }
    '/$tenant/admin/quizzes/$quizId/questions': {
      id: '/$tenant/admin/quizzes/$quizId/questions'
      path: '/questions'
      fullPath: '/$tenant/admin/quizzes/$quizId/questions'
      preLoaderRoute: typeof TenantAdminQuizzesQuizIdQuestionsRouteImport
      parentRoute: typeof TenantAdminQuizzesQuizIdRoute
    }
    '/$tenant/admin/courses/$courseId/edit': {
      id: '/$tenant/admin/courses/$courseId/edit'
      path: '/$courseId/edit'
      fullPath: '/$tenant/admin/courses/$courseId/edit'
      preLoaderRoute: typeof TenantAdminCoursesCourseIdEditRouteImport
      parentRoute: typeof TenantAdminCoursesRoute
    }
    '/$tenant/student/courses/$courseId/quiz/$quizId': {
      id: '/$tenant/student/courses/$courseId/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/$tenant/student/courses/$courseId/quiz/$quizId'
      preLoaderRoute: typeof TenantStudentCoursesCourseIdQuizQuizIdRouteImport
      parentRoute: typeof TenantStudentCoursesCourseIdRoute
    }
  }
}

interface TenantAdminCoursesRouteChildren {
  TenantAdminCoursesIndexRoute: typeof TenantAdminCoursesIndexRoute
  TenantAdminCoursesCourseIdEditRoute: typeof TenantAdminCoursesCourseIdEditRoute
}

const TenantAdminCoursesRouteChildren: TenantAdminCoursesRouteChildren = {
  TenantAdminCoursesIndexRoute: TenantAdminCoursesIndexRoute,
  TenantAdminCoursesCourseIdEditRoute: TenantAdminCoursesCourseIdEditRoute,
}

const TenantAdminCoursesRouteWithChildren =
  TenantAdminCoursesRoute._addFileChildren(TenantAdminCoursesRouteChildren)

interface TenantAdminQuizzesQuizIdRouteChildren {
  TenantAdminQuizzesQuizIdQuestionsRoute: typeof TenantAdminQuizzesQuizIdQuestionsRoute
  TenantAdminQuizzesQuizIdIndexRoute: typeof TenantAdminQuizzesQuizIdIndexRoute
}

const TenantAdminQuizzesQuizIdRouteChildren: TenantAdminQuizzesQuizIdRouteChildren =
  {
    TenantAdminQuizzesQuizIdQuestionsRoute:
      TenantAdminQuizzesQuizIdQuestionsRoute,
    TenantAdminQuizzesQuizIdIndexRoute: TenantAdminQuizzesQuizIdIndexRoute,
  }

const TenantAdminQuizzesQuizIdRouteWithChildren =
  TenantAdminQuizzesQuizIdRoute._addFileChildren(
    TenantAdminQuizzesQuizIdRouteChildren,
  )

interface TenantAdminQuizzesRouteChildren {
  TenantAdminQuizzesQuizIdRoute: typeof TenantAdminQuizzesQuizIdRouteWithChildren
  TenantAdminQuizzesIndexRoute: typeof TenantAdminQuizzesIndexRoute
}

const TenantAdminQuizzesRouteChildren: TenantAdminQuizzesRouteChildren = {
  TenantAdminQuizzesQuizIdRoute: TenantAdminQuizzesQuizIdRouteWithChildren,
  TenantAdminQuizzesIndexRoute: TenantAdminQuizzesIndexRoute,
}

const TenantAdminQuizzesRouteWithChildren =
  TenantAdminQuizzesRoute._addFileChildren(TenantAdminQuizzesRouteChildren)

interface TenantAdminUsersStudentIdRouteChildren {
  TenantAdminUsersStudentIdProgressRoute: typeof TenantAdminUsersStudentIdProgressRoute
  TenantAdminUsersStudentIdIndexRoute: typeof TenantAdminUsersStudentIdIndexRoute
}

const TenantAdminUsersStudentIdRouteChildren: TenantAdminUsersStudentIdRouteChildren =
  {
    TenantAdminUsersStudentIdProgressRoute:
      TenantAdminUsersStudentIdProgressRoute,
    TenantAdminUsersStudentIdIndexRoute: TenantAdminUsersStudentIdIndexRoute,
  }

const TenantAdminUsersStudentIdRouteWithChildren =
  TenantAdminUsersStudentIdRoute._addFileChildren(
    TenantAdminUsersStudentIdRouteChildren,
  )

interface TenantAdminUsersRouteChildren {
  TenantAdminUsersStudentIdRoute: typeof TenantAdminUsersStudentIdRouteWithChildren
  TenantAdminUsersNewRoute: typeof TenantAdminUsersNewRoute
  TenantAdminUsersIndexRoute: typeof TenantAdminUsersIndexRoute
}

const TenantAdminUsersRouteChildren: TenantAdminUsersRouteChildren = {
  TenantAdminUsersStudentIdRoute: TenantAdminUsersStudentIdRouteWithChildren,
  TenantAdminUsersNewRoute: TenantAdminUsersNewRoute,
  TenantAdminUsersIndexRoute: TenantAdminUsersIndexRoute,
}

const TenantAdminUsersRouteWithChildren =
  TenantAdminUsersRoute._addFileChildren(TenantAdminUsersRouteChildren)

interface TenantAdminRouteChildren {
  TenantAdminAnalyticsRoute: typeof TenantAdminAnalyticsRoute
  TenantAdminCertificatesRoute: typeof TenantAdminCertificatesRoute
  TenantAdminCoursesRoute: typeof TenantAdminCoursesRouteWithChildren
  TenantAdminLiveSessionsRoute: typeof TenantAdminLiveSessionsRoute
  TenantAdminProfileRoute: typeof TenantAdminProfileRoute
  TenantAdminQuizzesRoute: typeof TenantAdminQuizzesRouteWithChildren
  TenantAdminSecurityRoute: typeof TenantAdminSecurityRoute
  TenantAdminSettingsRoute: typeof TenantAdminSettingsRoute
  TenantAdminUsersRoute: typeof TenantAdminUsersRouteWithChildren
  TenantAdminIndexRoute: typeof TenantAdminIndexRoute
}

const TenantAdminRouteChildren: TenantAdminRouteChildren = {
  TenantAdminAnalyticsRoute: TenantAdminAnalyticsRoute,
  TenantAdminCertificatesRoute: TenantAdminCertificatesRoute,
  TenantAdminCoursesRoute: TenantAdminCoursesRouteWithChildren,
  TenantAdminLiveSessionsRoute: TenantAdminLiveSessionsRoute,
  TenantAdminProfileRoute: TenantAdminProfileRoute,
  TenantAdminQuizzesRoute: TenantAdminQuizzesRouteWithChildren,
  TenantAdminSecurityRoute: TenantAdminSecurityRoute,
  TenantAdminSettingsRoute: TenantAdminSettingsRoute,
  TenantAdminUsersRoute: TenantAdminUsersRouteWithChildren,
  TenantAdminIndexRoute: TenantAdminIndexRoute,
}

const TenantAdminRouteWithChildren = TenantAdminRoute._addFileChildren(
  TenantAdminRouteChildren,
)

interface TenantStudentCoursesCourseIdRouteChildren {
  TenantStudentCoursesCourseIdLearnRoute: typeof TenantStudentCoursesCourseIdLearnRoute
  TenantStudentCoursesCourseIdIndexRoute: typeof TenantStudentCoursesCourseIdIndexRoute
  TenantStudentCoursesCourseIdQuizQuizIdRoute: typeof TenantStudentCoursesCourseIdQuizQuizIdRoute
}

const TenantStudentCoursesCourseIdRouteChildren: TenantStudentCoursesCourseIdRouteChildren =
  {
    TenantStudentCoursesCourseIdLearnRoute:
      TenantStudentCoursesCourseIdLearnRoute,
    TenantStudentCoursesCourseIdIndexRoute:
      TenantStudentCoursesCourseIdIndexRoute,
    TenantStudentCoursesCourseIdQuizQuizIdRoute:
      TenantStudentCoursesCourseIdQuizQuizIdRoute,
  }

const TenantStudentCoursesCourseIdRouteWithChildren =
  TenantStudentCoursesCourseIdRoute._addFileChildren(
    TenantStudentCoursesCourseIdRouteChildren,
  )

interface TenantStudentCoursesRouteChildren {
  TenantStudentCoursesCourseIdRoute: typeof TenantStudentCoursesCourseIdRouteWithChildren
  TenantStudentCoursesIndexRoute: typeof TenantStudentCoursesIndexRoute
}

const TenantStudentCoursesRouteChildren: TenantStudentCoursesRouteChildren = {
  TenantStudentCoursesCourseIdRoute:
    TenantStudentCoursesCourseIdRouteWithChildren,
  TenantStudentCoursesIndexRoute: TenantStudentCoursesIndexRoute,
}

const TenantStudentCoursesRouteWithChildren =
  TenantStudentCoursesRoute._addFileChildren(TenantStudentCoursesRouteChildren)

interface TenantStudentRouteChildren {
  TenantStudentCoursesRoute: typeof TenantStudentCoursesRouteWithChildren
  TenantStudentLiveSessionsRoute: typeof TenantStudentLiveSessionsRoute
  TenantStudentProfileRoute: typeof TenantStudentProfileRoute
  TenantStudentProgressRoute: typeof TenantStudentProgressRoute
  TenantStudentIndexRoute: typeof TenantStudentIndexRoute
}

const TenantStudentRouteChildren: TenantStudentRouteChildren = {
  TenantStudentCoursesRoute: TenantStudentCoursesRouteWithChildren,
  TenantStudentLiveSessionsRoute: TenantStudentLiveSessionsRoute,
  TenantStudentProfileRoute: TenantStudentProfileRoute,
  TenantStudentProgressRoute: TenantStudentProgressRoute,
  TenantStudentIndexRoute: TenantStudentIndexRoute,
}

const TenantStudentRouteWithChildren = TenantStudentRoute._addFileChildren(
  TenantStudentRouteChildren,
)

interface TenantRouteChildren {
  TenantAdminRoute: typeof TenantAdminRouteWithChildren
  TenantLoginRoute: typeof TenantLoginRoute
  TenantStudentRoute: typeof TenantStudentRouteWithChildren
  TenantIndexRoute: typeof TenantIndexRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantAdminRoute: TenantAdminRouteWithChildren,
  TenantLoginRoute: TenantLoginRoute,
  TenantStudentRoute: TenantStudentRouteWithChildren,
  TenantIndexRoute: TenantIndexRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

interface SuperAdminRouteChildren {
  SuperAdminIdentitiesRoute: typeof SuperAdminIdentitiesRoute
  SuperAdminInvitationsRoute: typeof SuperAdminInvitationsRoute
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRoute
  SuperAdminTelemetryRoute: typeof SuperAdminTelemetryRoute
  SuperAdminTenantsRoute: typeof SuperAdminTenantsRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminIdentitiesRoute: SuperAdminIdentitiesRoute,
  SuperAdminInvitationsRoute: SuperAdminInvitationsRoute,
  SuperAdminSettingsRoute: SuperAdminSettingsRoute,
  SuperAdminTelemetryRoute: SuperAdminTelemetryRoute,
  SuperAdminTenantsRoute: SuperAdminTenantsRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenantRoute: TenantRouteWithChildren,
  LoginRoute: LoginRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  VerifyCertificateRoute: VerifyCertificateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
